/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import archivoz.lector;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;

/**
 *
 * @author ASUS
 */
public class interfaz extends javax.swing.JFrame {

    /**
     * Creates new form interfaz
     */
    private byte [] contenedor_bytes= null;
    public interfaz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        txt_tamaño = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_archivo = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        txt_terminado = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        txt_viru = new javax.swing.JTextArea();
        buscar = new javax.swing.JButton();
        analizarr = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_bytes1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_tamaño.setEditable(false);
        txt_tamaño.setBackground(new java.awt.Color(0, 0, 0));
        txt_tamaño.setColumns(20);
        txt_tamaño.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txt_tamaño.setForeground(new java.awt.Color(255, 255, 255));
        txt_tamaño.setRows(5);
        jScrollPane3.setViewportView(txt_tamaño);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 220, 70));

        txt_archivo.setEditable(false);
        txt_archivo.setBackground(new java.awt.Color(0, 0, 0));
        txt_archivo.setColumns(20);
        txt_archivo.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txt_archivo.setForeground(new java.awt.Color(255, 255, 255));
        txt_archivo.setRows(5);
        jScrollPane1.setViewportView(txt_archivo);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 630, 66));

        txt_terminado.setEditable(false);
        txt_terminado.setBackground(new java.awt.Color(0, 0, 0));
        txt_terminado.setColumns(20);
        txt_terminado.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txt_terminado.setForeground(new java.awt.Color(255, 255, 255));
        txt_terminado.setRows(5);
        jScrollPane4.setViewportView(txt_terminado);

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 520, 60));

        txt_viru.setEditable(false);
        txt_viru.setBackground(new java.awt.Color(0, 0, 0));
        txt_viru.setColumns(20);
        txt_viru.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txt_viru.setForeground(new java.awt.Color(255, 255, 255));
        txt_viru.setRows(5);
        jScrollPane5.setViewportView(txt_viru);

        getContentPane().add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 270, 520, 60));

        buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/search-button.jpg"))); // NOI18N
        buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarActionPerformed(evt);
            }
        });
        getContentPane().add(buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 100, 40, 40));

        analizarr.setBackground(new java.awt.Color(0, 248, 0));
        analizarr.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        analizarr.setForeground(new java.awt.Color(255, 255, 255));
        analizarr.setText("Analizar");
        analizarr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                analizarrActionPerformed(evt);
            }
        });
        getContentPane().add(analizarr, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 380, 130, 40));

        jButton3.setBackground(new java.awt.Color(0, 248, 0));
        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Limpiar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 383, 140, 40));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Antivirus-AnderCQ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 170, -1));

        txt_bytes1.setEditable(false);
        txt_bytes1.setBackground(new java.awt.Color(0, 0, 0));
        txt_bytes1.setColumns(20);
        txt_bytes1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txt_bytes1.setForeground(new java.awt.Color(255, 255, 255));
        txt_bytes1.setRows(5);
        txt_bytes1.setToolTipText("");
        jScrollPane2.setViewportView(txt_bytes1);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 150, 240));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/absolut-new-dimensions-sonar-d-sfpc-foto-1.jpg"))); // NOI18N
        jLabel1.setText("Antivirus_AnderCQ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarActionPerformed
        // TODO add your handling code here:
        
        JFileChooser explorador = new JFileChooser();
      explorador.showOpenDialog(this);
      File archivo = explorador.getSelectedFile();
      txt_archivo.setText(archivo.getPath());
      
      lector lectura= new lector(archivo);
      
        try {
            lectura.leer();
        } catch (IOException ex) {
            Logger.getLogger(interfaz.class.getName()).log(Level.SEVERE, null, ex);
        }
        contenedor_bytes= lectura.Bytes_Archivo();
        String cadena="";
        int i;
        String j;
        int u = 0;
        for(i=0; i<contenedor_bytes.length;i++){
            
            cadena= cadena+" "+contenedor_bytes[i]+"\n";
            
        }
        if(i==contenedor_bytes.length){
                txt_terminado.setText("!!Proceso terminado¡¡");
                txt_tamaño.setText(" "+contenedor_bytes.length+" bytes en el archivo");
            }
        txt_bytes1.setText(cadena);
        
    }//GEN-LAST:event_buscarActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
         txt_terminado.setText(" ");
         txt_bytes1.setText(" ");
         txt_tamaño.setText(" ");
          txt_archivo.setText(" ");
           txt_viru.setText(" ");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void analizarrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_analizarrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_analizarrActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton analizarr;
    private javax.swing.JButton buscar;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextArea txt_archivo;
    private javax.swing.JTextArea txt_bytes1;
    private javax.swing.JTextArea txt_tamaño;
    private javax.swing.JTextArea txt_terminado;
    private javax.swing.JTextArea txt_viru;
    // End of variables declaration//GEN-END:variables
}
